import type {
  InformationItem, MockSource, TopicItem, MockCluster, DailyReport, DashboardStats
} from '@/types'

export const mockStats: DashboardStats = {
  todayTotal: 147,
  highScoreCount: 23,
  newClusters: 8,
  pendingTopics: 12,
}

export const mockItems: InformationItem[] = [
  {
    id: 'item-001',
    title: 'OpenAI 发布 GPT-5：推理能力提升 3 倍，支持百万 token 上下文',
    summary: 'GPT-5 在 MMLU、HumanEval 等基准测试中全面超越前代，多模态能力大幅增强。',
    source: 'The Information',
    sourceTier: 'S',
    publishedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    category: 'AI技术',
    tags: ['OpenAI', 'GPT-5', 'LLM', '多模态'],
    finalScore: 94,
    scoreBreakdown: {
      ai_relevance: 96, source_score: 95, importance: 98, novelty: 90,
      momentum: 95, credibility: 92, actionability: 85, content_potential: 92, personal_fit: 88,
    },
    originalUrl: 'https://example.com/gpt5-launch',
    relatedReportCount: 47,
  },
  {
    id: 'item-002',
    title: 'Anthropic 完成 40 亿美元 C 轮融资，估值达 180 亿美元',
    summary: 'Google 和 Spark Capital 领投，Anthropic 将用于扩大模型训练规模和安全研究。',
    source: '华尔街日报',
    sourceTier: 'S',
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    category: '融资并购',
    tags: ['Anthropic', '融资', 'AI安全', 'Claude'],
    finalScore: 89,
    scoreBreakdown: {
      ai_relevance: 92, source_score: 95, importance: 91, novelty: 82,
      momentum: 88, credibility: 94, actionability: 78, content_potential: 85, personal_fit: 90,
    },
    originalUrl: 'https://example.com/anthropic-funding',
    relatedReportCount: 28,
  },
  {
    id: 'item-003',
    title: 'Meta 开源 Llama 3.2：70B 参数模型性能超越 GPT-4',
    summary: 'Llama 3.2 在代码生成和数学推理上显著提升，支持完全商业化使用。',
    source: 'Meta AI Blog',
    sourceTier: 'A',
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    category: '开源项目',
    tags: ['Meta', 'Llama', '开源', '大模型'],
    finalScore: 86,
    scoreBreakdown: {
      ai_relevance: 90, source_score: 80, importance: 88, novelty: 85,
      momentum: 92, credibility: 85, actionability: 80, content_potential: 88, personal_fit: 82,
    },
    originalUrl: 'https://example.com/llama32',
    relatedReportCount: 35,
  },
  {
    id: 'item-004',
    title: '欧盟 AI 法案正式生效：高风险 AI 系统须通过合规审查',
    summary: '企业有 24 个月过渡期，违规最高罚款为全球营业额的 3%。',
    source: 'Reuters',
    sourceTier: 'S',
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    category: '监管政策',
    tags: ['欧盟', 'AI法案', '合规', '监管'],
    finalScore: 82,
    scoreBreakdown: {
      ai_relevance: 78, source_score: 95, importance: 90, novelty: 72,
      momentum: 80, credibility: 95, actionability: 75, content_potential: 80, personal_fit: 70,
    },
    originalUrl: 'https://example.com/eu-ai-act',
    relatedReportCount: 19,
  },
  {
    id: 'item-005',
    title: 'Perplexity AI 推出企业版，月费 40 美元对标 ChatGPT Enterprise',
    summary: '内置实时网络搜索和引用功能，定位企业知识工作者市场。',
    source: 'TechCrunch',
    sourceTier: 'A',
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    category: '产品发布',
    tags: ['Perplexity', '企业版', 'AI搜索', 'SaaS'],
    finalScore: 79,
    scoreBreakdown: {
      ai_relevance: 82, source_score: 80, importance: 75, novelty: 80,
      momentum: 78, credibility: 82, actionability: 85, content_potential: 82, personal_fit: 78,
    },
    originalUrl: 'https://example.com/perplexity-enterprise',
    relatedReportCount: 12,
  },
  {
    id: 'item-006',
    title: 'Google DeepMind 发布 Gemini 1.5 Ultra：多模态理解进入新阶段',
    summary: '支持 200 万 token 上下文，可处理整部电影或代码库，视频理解能力领先行业。',
    source: 'Google DeepMind Blog',
    sourceTier: 'A',
    publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    category: 'AI技术',
    tags: ['Google', 'Gemini', '多模态', '长上下文'],
    finalScore: 88,
    scoreBreakdown: {
      ai_relevance: 94, source_score: 80, importance: 90, novelty: 88,
      momentum: 86, credibility: 85, actionability: 82, content_potential: 90, personal_fit: 85,
    },
    originalUrl: 'https://example.com/gemini15-ultra',
    relatedReportCount: 31,
  },
  {
    id: 'item-007',
    title: 'Microsoft 将 Copilot 深度集成至 Windows 12：AI 成操作系统基础设施',
    summary: '新版 Windows 所有系统级操作均可通过自然语言完成，本地模型优先处理隐私敏感任务。',
    source: 'The Verge',
    sourceTier: 'A',
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    category: '产品发布',
    tags: ['Microsoft', 'Copilot', 'Windows', 'AI操作系统'],
    finalScore: 83,
    scoreBreakdown: {
      ai_relevance: 86, source_score: 80, importance: 85, novelty: 80,
      momentum: 84, credibility: 82, actionability: 75, content_potential: 85, personal_fit: 80,
    },
    originalUrl: 'https://example.com/windows12-copilot',
    relatedReportCount: 22,
  },
  {
    id: 'item-008',
    title: 'Sam Altman：AGI 将在 2025 年某时点到来，但不会带来剧烈经济冲击',
    summary: 'Altman 在达沃斯演讲中预测 AGI 时间线，但强调就业影响将比预期温和。',
    source: 'Financial Times',
    sourceTier: 'S',
    publishedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    category: '人物动态',
    tags: ['Sam Altman', 'AGI', 'OpenAI', '预测'],
    finalScore: 77,
    scoreBreakdown: {
      ai_relevance: 85, source_score: 95, importance: 78, novelty: 68,
      momentum: 75, credibility: 88, actionability: 62, content_potential: 82, personal_fit: 75,
    },
    originalUrl: 'https://example.com/altman-agi-2025',
    relatedReportCount: 15,
  },
  {
    id: 'item-009',
    title: '字节跳动 AI 实验室发布豆包大模型 1.5，中文理解超越 GPT-4',
    summary: '在 CMMLU、C-Eval 等中文基准上领先，并发布针对内容创作的专版模型。',
    source: '36氪',
    sourceTier: 'B',
    publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    category: 'AI技术',
    tags: ['字节跳动', '豆包', '中文大模型', '内容创作'],
    finalScore: 71,
    scoreBreakdown: {
      ai_relevance: 80, source_score: 60, importance: 72, novelty: 70,
      momentum: 75, credibility: 68, actionability: 72, content_potential: 78, personal_fit: 82,
    },
    originalUrl: 'https://example.com/doubao-15',
    relatedReportCount: 8,
  },
  {
    id: 'item-010',
    title: '2024 年 AI 投资总额突破 1000 亿美元，创历史新高',
    summary: '其中生成式 AI 占比 65%，基础模型公司吸引最多资本，应用层竞争日趋激烈。',
    source: 'CB Insights',
    sourceTier: 'A',
    publishedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    category: '研究报告',
    tags: ['AI投资', '行业报告', '生成式AI', '融资趋势'],
    finalScore: 75,
    scoreBreakdown: {
      ai_relevance: 80, source_score: 80, importance: 78, novelty: 65,
      momentum: 70, credibility: 85, actionability: 70, content_potential: 80, personal_fit: 72,
    },
    originalUrl: 'https://example.com/ai-investment-2024',
    relatedReportCount: 10,
  },
  {
    id: 'item-011',
    title: 'Stability AI 申请破产保护，AI 绘画赛道进入整合期',
    summary: '创始人 Emad Mostaque 离职后公司持续亏损，债权人已启动重组谈判。',
    source: 'Bloomberg',
    sourceTier: 'S',
    publishedAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    category: '商业动态',
    tags: ['Stability AI', 'AI绘画', '破产', 'Midjourney'],
    finalScore: 80,
    scoreBreakdown: {
      ai_relevance: 78, source_score: 95, importance: 82, novelty: 78,
      momentum: 82, credibility: 92, actionability: 68, content_potential: 85, personal_fit: 72,
    },
    originalUrl: 'https://example.com/stability-bankruptcy',
    relatedReportCount: 18,
  },
  {
    id: 'item-012',
    title: '苹果 Apple Intelligence 正式落地：Siri 升级为对话式 AI 助手',
    summary: '结合本地模型与 ChatGPT 云端，优先处理敏感数据，功能逐步向全球用户推出。',
    source: 'MacRumors',
    sourceTier: 'B',
    publishedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    category: '产品发布',
    tags: ['Apple', 'Apple Intelligence', 'Siri', 'on-device AI'],
    finalScore: 68,
    scoreBreakdown: {
      ai_relevance: 72, source_score: 60, importance: 70, novelty: 65,
      momentum: 72, credibility: 72, actionability: 65, content_potential: 70, personal_fit: 68,
    },
    originalUrl: 'https://example.com/apple-intelligence-launch',
    relatedReportCount: 7,
  },
  {
    id: 'item-013',
    title: 'Hugging Face 推出 SmolLM：专为边缘设备设计的 1B 参数高效模型',
    summary: '在手机和嵌入式设备上实现接近大模型的推理质量，完全开源。',
    source: 'Hugging Face Blog',
    sourceTier: 'A',
    publishedAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    category: '开源项目',
    tags: ['Hugging Face', 'SmolLM', '边缘计算', '小模型'],
    finalScore: 73,
    scoreBreakdown: {
      ai_relevance: 82, source_score: 80, importance: 70, novelty: 78,
      momentum: 68, credibility: 82, actionability: 75, content_potential: 72, personal_fit: 80,
    },
    originalUrl: 'https://example.com/smollm',
    relatedReportCount: 6,
  },
  {
    id: 'item-014',
    title: '中国 AI 行业报告：国内大模型应用落地速度超预期，B 端付费意愿提升',
    summary: '调研显示 62% 的中大型企业已开始评估或部署 AI 助手，医疗和法律行业增速最快。',
    source: '中国信通院',
    sourceTier: 'A',
    publishedAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    category: '研究报告',
    tags: ['中国AI', '行业报告', 'B端应用', '企业AI'],
    finalScore: 70,
    scoreBreakdown: {
      ai_relevance: 78, source_score: 80, importance: 72, novelty: 65,
      momentum: 68, credibility: 80, actionability: 72, content_potential: 75, personal_fit: 70,
    },
    originalUrl: 'https://example.com/china-ai-report',
    relatedReportCount: 5,
  },
  {
    id: 'item-015',
    title: 'Runway Gen-4 发布：视频生成质量达到专业影视制作水准',
    summary: '支持角色一致性和摄像机精准控制，首批合作伙伴包括好莱坞三家主要制片厂。',
    source: 'Variety',
    sourceTier: 'B',
    publishedAt: new Date(Date.now() - 40 * 60 * 60 * 1000).toISOString(),
    category: 'AI技术',
    tags: ['Runway', '视频生成', 'AI影视', '创意工具'],
    finalScore: 76,
    scoreBreakdown: {
      ai_relevance: 80, source_score: 60, importance: 78, novelty: 82,
      momentum: 78, credibility: 72, actionability: 78, content_potential: 85, personal_fit: 75,
    },
    originalUrl: 'https://example.com/runway-gen4',
    relatedReportCount: 9,
  },
]

export const mockSources: MockSource[] = [
  {
    id: 'src-001',
    name: 'The Information',
    url: 'https://theinformation.com/feed',
    tier: 'S',
    category: '商业动态',
    enabled: true,
    lastFetchedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    itemsToday: 8,
    avgScore: 82,
    description: '科技行业深度报道，付费独家内容，信源质量极高',
  },
  {
    id: 'src-002',
    name: '华尔街日报',
    url: 'https://wsj.com/xml/rss/3_7455.xml',
    tier: 'S',
    category: '商业动态',
    enabled: true,
    lastFetchedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    itemsToday: 12,
    avgScore: 78,
    description: '全球顶级财经媒体，商业和科技新闻权威来源',
  },
  {
    id: 'src-003',
    name: 'TechCrunch',
    url: 'https://techcrunch.com/feed/',
    tier: 'A',
    category: '产品发布',
    enabled: true,
    lastFetchedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    itemsToday: 24,
    avgScore: 65,
    description: '创业公司和产品发布的重要信源，噪声较多但覆盖面广',
  },
  {
    id: 'src-004',
    name: 'Hugging Face Blog',
    url: 'https://huggingface.co/blog/feed.xml',
    tier: 'A',
    category: 'AI技术',
    enabled: true,
    lastFetchedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    itemsToday: 3,
    avgScore: 74,
    description: 'AI/ML 开源社区第一平台，技术深度高',
  },
  {
    id: 'src-005',
    name: 'Bloomberg Technology',
    url: 'https://bloomberg.com/feed/technology',
    tier: 'S',
    category: '商业动态',
    enabled: true,
    lastFetchedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    itemsToday: 15,
    avgScore: 76,
    description: '金融与科技的交叉报道，资本市场视角',
  },
  {
    id: 'src-006',
    name: '36氪',
    url: 'https://36kr.com/feed',
    tier: 'B',
    category: '商业动态',
    enabled: true,
    lastFetchedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    itemsToday: 38,
    avgScore: 52,
    description: '中国创投媒体，覆盖面广，噪声较多',
  },
  {
    id: 'src-007',
    name: 'Reuters Technology',
    url: 'https://feeds.reuters.com/reuters/technologyNews',
    tier: 'S',
    category: '监管政策',
    enabled: true,
    lastFetchedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    itemsToday: 10,
    avgScore: 71,
    description: '全球新闻通讯社，政策和监管报道权威',
  },
  {
    id: 'src-008',
    name: 'The Verge',
    url: 'https://theverge.com/rss/index.xml',
    tier: 'A',
    category: '产品发布',
    enabled: true,
    lastFetchedAt: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    itemsToday: 20,
    avgScore: 61,
    description: '消费科技和产品评测，读者友好',
  },
  {
    id: 'src-009',
    name: 'CB Insights',
    url: 'https://cbinsights.com/research/feed',
    tier: 'A',
    category: '研究报告',
    enabled: false,
    lastFetchedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    itemsToday: 0,
    avgScore: 68,
    description: '行业数据和融资报告，目前已暂停抓取',
  },
]

export const mockTopics: TopicItem[] = [
  {
    id: 'topic-001',
    sourceItemId: 'item-001',
    topicTitle: 'GPT-5 对内容创作行业的影响：机遇还是威胁？',
    coreInfo: 'GPT-5 推理能力提升 3 倍，长上下文支持使得内容创作的 AI 替代性进一步增强',
    possibleAngles: [
      '哪些内容类型最先被替代？',
      '创作者如何用 GPT-5 做差异化而非被替代',
      '对内容付费市场的影响',
    ],
    targetPlatform: '公众号',
    targetReader: '内容创作者、自媒体人、写作从业者',
    readerPainPoint: '担心被 AI 取代，不知道如何定位自己的价值',
    priority: 'high',
    status: 'worth_writing',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'topic-002',
    sourceItemId: 'item-004',
    topicTitle: '欧盟 AI 法案落地：中国企业出海需要准备什么',
    coreInfo: '高风险 AI 系统须通过合规审查，最高罚款 3% 全球营收，中国企业出欧面临新门槛',
    possibleAngles: [
      '哪些中国 AI 产品会受影响？',
      '合规成本测算与准备清单',
      '欧盟 vs 美国 vs 中国 AI 监管对比',
    ],
    targetPlatform: '知乎',
    targetReader: '关注出海和 AI 合规的从业者',
    readerPainPoint: '对 AI 监管政策细节不了解，不知道如何准备',
    priority: 'high',
    status: 'pending',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'topic-003',
    sourceItemId: 'item-011',
    topicTitle: 'Stability AI 倒下的启示：AI 创业公司的生存法则',
    coreInfo: '创始人出走 + 商业模式存疑 + 资本退潮，AI 绘画赛道第一名陨落',
    possibleAngles: [
      '为什么开源路线在 AI 很难盈利？',
      'Midjourney vs Stability AI 商业模式对比',
      '下一个可能倒下的 AI 独角兽是谁？',
    ],
    targetPlatform: '公众号',
    targetReader: 'AI 创业者、投资人、科技从业者',
    readerPainPoint: '想从失败案例中学习 AI 创业教训',
    priority: 'medium',
    status: 'writing',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'topic-004',
    sourceItemId: 'item-010',
    topicTitle: '1000 亿美元流向哪里：2024 AI 投资全景图',
    coreInfo: '生成式 AI 占比 65%，基础模型吸金最多，应用层竞争白热化',
    possibleAngles: [
      '哪些方向已经过热？',
      '仍有机会的 AI 投资细分领域',
      '散户和小创业者的机会在哪',
    ],
    targetPlatform: '小红书',
    targetReader: '关注科技投资的年轻人',
    readerPainPoint: '想了解 AI 投资动向但信息太分散',
    priority: 'medium',
    status: 'pending',
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'topic-005',
    sourceItemId: 'item-003',
    topicTitle: 'Llama 3.2 完全开源对 AI 产品开发的影响',
    coreInfo: '70B 参数模型可商用，降低了构建 AI 产品的门槛，但同时加剧了同质化',
    possibleAngles: [
      '用 Llama 3.2 能做什么商业化产品？',
      '哪些现有 API 服务会被替代？',
      '开源和闭源的长期竞争格局',
    ],
    targetPlatform: '即刻',
    targetReader: 'AI 开发者和独立开发者',
    readerPainPoint: '想快速评估新开源模型的实际价值',
    priority: 'low',
    status: 'abandoned',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'topic-006',
    sourceItemId: 'item-006',
    topicTitle: 'Gemini 200 万 token 上下文：哪些工作流程会被重塑',
    coreInfo: '200 万 token 可容纳整部代码库或电影，使得"一次性处理整体"成为可能',
    possibleAngles: [
      '法律合规文档审查的变革',
      '代码库分析和重构',
      '学术研究文献处理',
    ],
    targetPlatform: '内部报告',
    targetReader: '企业技术决策者',
    readerPainPoint: '想知道超长上下文实际能解决哪些业务问题',
    priority: 'high',
    status: 'worth_writing',
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockClusters: MockCluster[] = [
  {
    id: 'cluster-001',
    title: 'GPT-5 发布事件',
    primaryItemId: 'item-001',
    relatedItemIds: ['item-008'],
    sourceCount: 47,
    firstSeenAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    latestAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    momentum: 98,
    category: 'AI技术',
  },
  {
    id: 'cluster-002',
    title: 'Anthropic C 轮融资',
    primaryItemId: 'item-002',
    relatedItemIds: [],
    sourceCount: 28,
    firstSeenAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    latestAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    momentum: 72,
    category: '融资并购',
  },
  {
    id: 'cluster-003',
    title: '欧盟 AI 监管政策',
    primaryItemId: 'item-004',
    relatedItemIds: [],
    sourceCount: 19,
    firstSeenAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    latestAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    momentum: 55,
    category: '监管政策',
  },
  {
    id: 'cluster-004',
    title: 'Stability AI 危机',
    primaryItemId: 'item-011',
    relatedItemIds: [],
    sourceCount: 18,
    firstSeenAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    latestAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    momentum: 65,
    category: '商业动态',
  },
]

export const mockReports: DailyReport[] = [
  {
    id: 'report-2026-05-28',
    date: '2026-05-28',
    summary: [
      'GPT-5 正式发布，推理能力提升显著，行业格局面临重塑',
      'Anthropic 完成历史最大轮融资，AI 安全赛道资本持续涌入',
      '欧盟 AI 法案生效，高风险 AI 系统合规要求正式落地',
      'Stability AI 申请破产，AI 绘画赛道进入整合期',
      '国内大模型应用落地速度超预期，B 端付费意愿明显提升',
    ],
    topStories: [
      { title: 'GPT-5 发布：推理能力提升 3 倍', summary: '多模态和长上下文全面升级', score: 94 },
      { title: 'Anthropic 40 亿美元 C 轮', summary: 'Google 领投，估值 180 亿', score: 89 },
      { title: 'Gemini 1.5 Ultra 上线', summary: '200 万 token，视频理解领先', score: 88 },
      { title: '欧盟 AI 法案正式生效', summary: '企业有 24 个月过渡期', score: 82 },
      { title: 'Stability AI 破产申请', summary: '创始人出走后持续亏损', score: 80 },
    ],
    trendingTopics: ['GPT-5', '欧盟AI监管', 'AI融资', '开源大模型', '视频生成'],
    contentAngles: [
      'GPT-5 对内容创作者的实际影响：机遇与威胁',
      '欧盟 AI 法案中国企业出海合规指南',
      'Stability AI 倒下给 AI 创业者的 5 个教训',
      'AI 投资 1000 亿之后，钱流向哪里',
    ],
    generatedAt: new Date().toISOString(),
  },
]
